// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace todo_list.Models
{
    [Table("List")]
    public partial class List
    {
        public List()
        {
            Tasks = new HashSet<Task>();
        }

        [Key]
        public int id { get; set; }
        [Unicode(false)]
        public string name { get; set; }
        [StringLength(50)]
        [Unicode(false)]
        public string color { get; set; }

        [InverseProperty("List")]
        public virtual ICollection<Task> Tasks { get; set; }
    }
}